### PR TITLE
Serialize pydantic events before creating OTEL spans

### LINKED ISSUE #63: OpenTelemetry breaks when events are Pydantic models
I am instrumenting a FastAPI application where events are Pydantic models, but the OTEL implementation expects them to be `dict`. This causes the following error on each event:

```
  File \"/path/.venv/lib/python3.11/site-packages/fastapi_events/dispatcher.py\", line 52, in task
    await asyncio.gather(*[handler.handle((event_name, payload)) for handler in handlers])
  File \"/path/.venv/lib/python3.11/site-packages/fastapi_events/handlers/local.py\", line 195, in handle
    with create_span_for_handle_fn(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/fastapi_events/otel/utils.py\", line 47, in create_span_for_handle_fn
    remote_ctx = propagate.extract(payload)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/opentelemetry/propagate/__init__.py\", line 101, in extract
    return get_global_textmap().extract(carrier, context, getter=getter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/opentelemetry/propagators/composite.py\", line 52, in extract
    context = propagator.extract(carrier, context, getter=getter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/opentelemetry/trace/propagation/tracecontext.py\", line 49, in extract
    header = getter.get(carrier, self._TRACEPARENT_HEADER_NAME)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/opentelemetry/propagators/textmap.py\", line 87, in get
    val = carrier.get(key, None)
          ^^^^^^^^^^^
  File \"/path/.venv/lib/python3.11/site-packages/pydantic/main.py\", line 811, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'QueueItemStatusChangedEvent' object has no attribute 'get'"}
```

`payload` (a Pydantic model) does not have a `.get()` method, so this exception is raised. I can not bypass this either, because when opentelemetry packages are installed in the venv, `fastapi-events` imports them and attempts to instrument itself automatically.

Is there any way to either:
- pass a different `getter` method or somehow configure the OpenTelemetry propagator differently to handle Pydantic models (i know this is beyond the scope of `fastapi-events`, but couldn't find any docs on this)
- turn off instrumentation in `fastapi-events` altogether, so that I can use the OpenTelemetry fastapi contrib libraries to instrument the application?

Thanks for any help.
(ETA: it's definitely possible that i have no idea what i'm doing)

### PR DESCRIPTION
**Pull request by ebr**
OpenTelemetry `propagate.extract()` method is unable to handle Pydantic models, so they must be serialized before creating spans. Looks like the issue was introduced with #57 and only appears when Pydantic model schema dump is turned off.

In this PR we also determine the event name before creating the span. Otherwise all `dispatch` spans are named `Event None dispatched` - now the actual event name is set instead of None.

Fixes #63

### CODE REVIEW

File: fastapi_events/dispatcher.py [hunk 1]
```diff
@@ -290,7 +292,7 @@ class UserCreated(pydantic.BaseModel):
                 )
 
         # OTEL
-        if payload and isinstance(payload, dict):
```
Comment (ebr) [inline fastapi_events/dispatcher.py:293]: Not sure why this type check was needed here, and whether injecting traceparent is needed for every payload or only some.

File: fastapi_events/otel/utils.py [hunk 2]
```diff
@@ -39,6 +40,9 @@ def create_span_for_handle_fn(
 
     links, context = [], None
 
+    if isinstance(payload, BaseModel):
```
Comment (melvinkcx) [inline fastapi_events/otel/utils.py]: Hi, thanks for your contribution :) 

Even though the package is called `fastapi_events`, I know there are some users using it without FastAPI and Pydantic. So, importing `pydantic` will break those use cases. 

Instead of importing BaseModel from pydantic, I suggest using duck typing to maximise backward compatibility. 

Also, IIRC, the `model_dump` method was introduced in Pydantic v2. It replaced the `dict()` method in v1.

I'd suggest something like:

```python
if hasattr(payload, "model_dump"):  # handle Pydantic v2
    payload = payload.model_dump()
elif hasattr(payload, "dict"):    # handles Pydantic v1
    payload = payload.dict()     
```

In fact, we have similar logic handling both pydantic versions and the absence of pydantic in the dispatcher just fyi:
- https://github.com/melvinkcx/fastapi-events/blob/f44705b4031435d42f6e34bcf635c5d69f8bfdff/fastapi_events/dispatcher.py#L22
- https://github.com/melvinkcx/fastapi-events/blob/f44705b4031435d42f6e34bcf635c5d69f8bfdff/fastapi_events/dispatcher.py#L156

Once you update the changes, I'll be sure to have it merged asap. Thanks again for your contribution :)

**Review by melvinkcx — CHANGES_REQUESTED** [review]

File: fastapi_events/otel/utils.py (hunk 2 above)
Comment (ebr) [reply fastapi_events/otel/utils.py]: I updated the changes as you recommended. Duck typing seemed less verbose in this case than duplicating the `HAS_PYDANTIC`... logic from the dispatcher, but i'd be fine with either approach.

File: fastapi_events/dispatcher.py (hunk 1 above)
Comment (ebr) [reply fastapi_events/dispatcher.py:293]: @melvinkcx I don't see the removal of this typing check breaking anything, but let me know please if i'm missing something.

Also, in this PR we're serializing the Pydantic payload for OTEL inside both `create_span_for_handle_fn()`  and `inject_traceparent()` . Do you think there's a performance penalty here that is worth spending the time to optimize?

Thank you for this great library :)

Comment (melvinkcx) [reply fastapi_events/dispatcher.py:293]: IIRC, the `isinstance(payload, dict)` was added just in case people are using a custom class instance as payload. In this case, we should avoid injecting traceparent, since it most likely wont work.

File: fastapi_events/otel/utils.py (hunk 2 above)
Comment (melvinkcx) [reply fastapi_events/otel/utils.py]: Thanks, it works for me

File: fastapi_events/dispatcher.py (hunk 1 above)
Comment (melvinkcx) [reply fastapi_events/dispatcher.py:293]: For the performance penalty, I see your point. I don't have any numbers on hand as for how much performance penalty it introduces, but I wouldn't mind us fixing it

**Review by melvinkcx — APPROVED** [review]
